name: "Auto-merge"

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - ready_for_review

jobs:
  call-workflow:
    permissions: {}
    uses: nexus-module/.github/.github/workflows/github-automerge.yml@main
    secrets:
      PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
