name: "Mark or close stale issues and PRs"

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  call-workflow:
    permissions:
      issues: write
      pull-requests: write
    uses: nexus-module/.github/.github/workflows/reusable-stale.yml@main
